doc: fix wallet name issue in execute command
The transfer execute transaction should use `wallet` rather than `wallet2` to perform the call since the owner is the account associated to `wallet` key.
With the current sample command the execution gives an error:
```
Error: rpc error: code = InvalidArgument desc = failed to execute message; message index: 0: Unauthorized: execute wasm contract failed: invalid request
```
Which makes sense since `wallet2` is not the owner of `fred` record.